### ISSUE TITLE
Gracefully fail on 404 responses

### ISSUE THREAD

**Issue by jdenoc** [jdenoc/doxie-consumer#20]
Got the following stack trace from with a `404` response from the doxie scanner when calling `GET /scans.json`
```
[2017-03-02T00:41:44+00:00] doxie-consumer.ERROR: Failed to list scans exception 'Guzzle\Http\Exception\ClientErrorResponseException' with message 'Client error response [status code] 404 [reason phrase] No Content [url] http://doxie/scans.json' in phar:///opt/cron/doxie-consumer.phar/vendor/guzzle/guzzle/src/Guzzle/Http/Exception/BadResponseException.php:43
Stack trace:
  #0 phar:///opt/cron/doxie-consumer.phar/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(145): Guzzle\Http\Exception\BadResponseException::factory(Object(Guzzle\Http\Message\Request), Object(Guzzle\Http\Message\Response))
  #1 [internal function]: Guzzle\Http\Message\Request::onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
  #2 phar:///opt/cron/doxie-consumer.phar/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Array, Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
  #3 phar:///opt/cron/doxie-consumer.phar/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\Common\Event))
  #4 phar:///opt/cron/doxie-consumer.phar/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(589): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('request.error', Object(Guzzle\Common\Event))
  #5 phar:///opt/cron/doxie-consumer.phar/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(378): Guzzle\Http\Message\Request->processResponse(Array)
  #6 phar:///opt/cron/doxie-consumer.phar/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(303): Guzzle\Http\Message\Request->setState('complete', Array)
  #7 phar:///opt/cron/doxie-consumer.phar/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\Request), Object(Guzzle\Http\Curl\CurlHandle), Array)
  #8 phar:///opt/cron/doxie-consumer.phar/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(240): Guzzle\Http\Curl\CurlMulti->processMessages()
  #9 phar:///opt/cron/doxie-consumer.phar/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(224): Guzzle\Http\Curl\CurlMulti->executeHandles()
  #10 phar:///opt/cron/doxie-consumer.phar/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(111): Guzzle\Http\Curl\CurlMulti->perform()
  #11 phar:///opt/cron/doxie-consumer.phar/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMultiProxy.php(94): Guzzle\Http\Curl\CurlMulti->send()
  #12 phar:///opt/cron/doxie-consumer.phar/vendor/guzzle/guzzle/src/Guzzle/Http/Client.php(284): Guzzle\Http\Curl\CurlMultiProxy->send()
  #13 phar:///opt/cron/doxie-consumer.phar/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(198): Guzzle\Http\Client->send(Object(Guzzle\Http\Message\Request))
  #14 phar:///opt/cron/doxie-consumer.phar/src/DoxieConsumer.php(97): Guzzle\Http\Message\Request->send()
  #15 phar:///opt/cron/doxie-consumer.phar/src/consumer.php(57): DoxieConsumer->list_scans()
  #16 /opt/cron/doxie-consumer.phar(12): require('phar:///opt/cro...')
  #17 {main}
```

There's an aweful lot of stuff here and we don't really need to see it. Maybe _404 exceptions_ should be turned off.

**Comment by jdenoc** [comment]
Is fixed by #22
